### ISSUE TITLE
not work

### ISSUE THREAD

**Issue by blackout314** [Alexintosh/Ionic-BigBang#1]
i'm cordova newbie (and ionic too)
i tried to install and took this error when i opened www/index.html

```
GET file:///home/cdenaro/GIT/Ionic-BigBang/www/cordova.js net::ERR_FILE_NOT_FOUND
ionic.bundle.js:19341 XMLHttpRequest cannot load file:///home/cdenaro/GIT/Ionic-BigBang/www/templates/settings.html. Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, https, chrome-extension-resource.(anonymous function) @ ionic.bundle.js:19341sendReq @ ionic.bundle.js:19160$get.serverRequest @ ionic.bundle.js:18872processQueue @ ionic.bundle.js:23394(anonymous function) @ ionic.bundle.js:23410$get.Scope.$eval @ ionic.bundle.js:24673$get.Scope.$digest @ ionic.bundle.js:24484$get.Scope.$apply @ ionic.bundle.js:24778bootstrapApply @ ionic.bundle.js:10460invoke @ ionic.bundle.js:13277doBootstrap @ ionic.bundle.js:10458bootstrap @ ionic.bundle.js:10478angularInit @ ionic.bundle.js:10372(anonymous function) @ ionic.bundle.js:37186trigger @ ionic.bundle.js:11823eventHandler @ ionic.bundle.js:12098
ionic.bundle.js:21157 Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///home/cdenaro/GIT/Ionic-BigBang/www/templates/settings.html'.
    at Error (native)
    at file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:19341:11
    at sendReq (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:19160:9)
    at $get.serverRequest (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:18872:16)
    at processQueue (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:23394:28)
    at file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:23410:27
    at Scope.$get.Scope.$eval (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:24673:28)
    at Scope.$get.Scope.$digest (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:24484:31)
    at Scope.$get.Scope.$apply (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:24778:24)
    at bootstrapApply (file:///home/cdenaro/GIT/Ionic-BigBang/www/lib/ionic/js/ionic.bundle.js:10460:15)
```

**Comment by Alexintosh** [comment]
I had no time to write the installation guide, I will tonight, stay tuned

**Comment by blackout314** [comment]
gr8

**Comment by Alexintosh** [comment]
check the README ;) hope it helps!

**Comment by blackout314** [comment]
ty mate
